Fix error in logs formatting
TypeError: %d format: a number is required, not unicode
Logged from file dlrn_interface.py, line 257

Change-Id: I4b420320d2d925a424afe76ba88d403332638cbb