Update tests to run on Py 3.9
Due to a bug in OpenStackSDK [1], the library is marked as Python 3.6
compatible, however it uses features from Python 3.8 and later.
It is causing AttributeError:

> AttributeError: module 'typing' has no attribute 'Literal'

Updating tests configuration to run on latest available python version.

[1]: https://storyboard.openstack.org/#!/story/2010903

Change-Id: I1bd033924a76880a507a88b05d3af292b3117c12