Fix missing markupsafe
2019-09-30 03:14:04,779 1665 ERROR    promoter CONTAINER IMAGE UPLOAD FAILED LOGS BELOW:
2019-09-30 03:14:04,779 1665 ERROR    promoter Traceback (most recent call last):
  File "/home/centos/promoter_venv/bin/ansible-playbook", line 60, in <module>
    import ansible.constants as C
  File "/home/centos/promoter_venv/lib/python2.7/site-packages/ansible/constants.py", line 12, in <module>
    from jinja2 import Template
  File "/home/centos/promoter_venv/lib/python2.7/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/home/centos/promoter_venv/lib/python2.7/site-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/home/centos/promoter_venv/lib/python2.7/site-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/home/centos/promoter_venv/lib/python2.7/site-packages/jinja2/utils.py", line 647, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: No module named markupsafe

Change-Id: I7411196390c1d6caab4ddf694143b6bb1240aaff
See: http://38.145.34.55/centos7_master.log