Add missing `verify=CERT_PATH`
python-requests is using by default certify and its embedded CA bundle,
based on Mozilla accepted CA.

Other `requests.get` are allowing to override the bundle.

The error we hit is as follow:
$ ruck-rover --release osp18 --distro rhel-9
[...]
File "[...]/ci-config/ci-scripts/infra-setup/roles/rrcockpit/files/telegraf_py3/ruck_rover.py", line 381, in get_job_history
[...]
requests.exceptions.SSLError: HTTPSConnectionPool(host='HOST', port=443): Max retries exceeded
[...]

Change-Id: I958e093114f7233c49b6676e929321f4d0bb8ed9