Added missing 'click' dependency
When trying to use ruck_rover, it complained about missing 'click'
dependency.
  ModuleNotFoundError: No module named 'click'

Added missing dependency to requirements.

Change-Id: I5ecec938c45500a5ccb637c91a1b4fb63fb987fc