Fix find_jobs_in_component_criteria method if no job found
When we design a new pipeline, then we keep the component job
criteria empty like this.
```
promoted-components:
  baremetal:
  cinder:
```
When ruck_rover.py tools reads the above criteria file,
then find_jobs_in_component_criteria returns None and fails
the tool with following error:
```
ruck_rover.py", line 129, in find_jobs_in_component_criteria
    return set(criteria['promoted-components'][component])
TypeError: 'NoneType' object is not iterable
```
As an None list cannot be converted to set due to immutable
nature of set. Setting the returns to empty list fixes the
issue.

Signed-off-by: Chandan Kumar (raukadah) <chkumar@redhat.com>
Change-Id: I112ec4c4bf77e93b13421ae3a9bfe58a6b2b0c70